spring:
  data:
    mongodb:
#      uri: mongodb://localhost:27017/Mediani
      authentication-database: admin
      username: ${MONGO_DB_ID}
      password: ${MONGO_DB_PW}
      host: ${MONGO_DB_IP}
      port: ${MONGO_DB_PORT}
      database: Mediani
      auto-index-creation: true